version: '3.8'
services:
  db:
    image: postgis/postgis:13-3.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gislib
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/gislib
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8083:8080"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        VITE_API_BASE: ${VITE_API_BASE:-http://121.48.161.82:8083/api}
    ports:
      - "5173:80"
    depends_on:
      - backend

  tester:
    build:
      context: .
      dockerfile: scripts/Dockerfile
    environment:
      BACKEND_URL: http://backend:8080/api
      PG_HOST: db
      PG_PORT: 5432
      PG_USER: postgres
      PG_PASS: postgres
      PG_DB: gislib
    depends_on:
      - db
      - backend
    restart: "no"
    profiles:
      - tester

volumes:
  db-data:
